name: Update Currency Rates

on:
#  schedule:
    # Uruchamiaj dla czasu UTC 
 #   - cron: '0 8 * * *'
  #  - cron: '0 17 * * *'
  workflow_dispatch: # Pozwala uruchomić ręcznie dla testu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          FIXER_API_KEY: ${{ secrets.FIXER_API_KEY }}
        run: python update_rates.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "Currency Bot"
          git config --global user.email "bot@github.com"
          git add rates.json
          git commit -m "Automatyczna aktualizacja kursów: $(date)" || exit 0
          git push
